license="GPL-3.0-or-later"
[[mods]]
modId="reforgedplaymod"
version="0.4"
displayName="ReForgedPlay Mod"
displayTest = "IGNORE_SERVER_VERSION"
logoFile = "logo.png"
authors="CrushedPixel, johni0702, Ferri_Arnus"
description='''
A Mod which allows you to record, replay and share your Minecraft experience.
'''

[modproperties.reforgedplaymod]
"frex:flawless_frames_handler" = "com.replaymod.render.utils.SodiumFlawlessFrames"

[[dependencies.reforgedplaymod]]
modId = "neoforge"
type="required"
versionRange = "[26.1.2.76,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reforgedplaymod]]
modId = "minecraft"
type="required"
versionRange = "[26.1,26.2)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "mixins.compat.mapwriter.replaymod.json"

[[mixins]]
config = "mixins.compat.shaders.replaymod.json"

[[mixins]]
config = "mixins.core.replaymod.json"

[[mixins]]
config = "mixins.extras.playeroverview.replaymod.json"

[[mixins]]
config = "mixins.jgui.json"

[[mixins]]
config = "mixins.nonmmlauncher.replaymod.json"

[[mixins]]
config = "mixins.recording.replaymod.json"

[[mixins]]
config = "mixins.render.blend.replaymod.json"

[[mixins]]
config = "mixins.render.replaymod.json"

[[mixins]]
config = "mixins.replay.replaymod.json"

[[mods]]
modId="replaymod"
version="2.6.26"
displayName="Replay Mod"
license="GPL-3.0-or-later"
displayTest = "IGNORE_SERVER_VERSION"
logoFile="assets/replaymod/favicon_logo.png"
authors="CrushedPixel, johni0702"
description='''
A Mod which allows you to record, replay and share your Minecraft experience.
'''
